In [ ]:
x = [1,2,3]
y = [2,3,4]
ans = []
for a,b in zip(x,y):
    v = a + b
    ans.append(v)
print(ans)

In [ ]:
x = [[1,2], [3,4]]
y = [[2,3], [4,5]]

number processing libary for python - numpy
- array : it is a list of homogenous elements

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
y = np.array([2,3,4])
print(x,'+',y,'=',x+y)
print(x,'-',y,'=',x-y)
print(x,'*',y,'=',x*y)
print(x,'/',y,'=',x/y)

matrices are 
- 1D array
- 2D array
- 3D array
- 4D array
- nD array

In [ ]:
# one dimension matrix
x = np.array([1,2,3])
print(x, type(x), x.shape, x.ndim)
# two dimension matrix
x2 = np.array([[1,2],[3,4]])
print(x2, type(x2), x2.shape, x2.ndim)

In [ ]:
# 3 dimension matrix
x3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3, x3.shape, x3.ndim, x3.size)

In [ ]:
# 6 x 6 matrix
x4 = np.array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
    [1,2,3,4,5,6],
])
print(x4.shape, x4.ndim, x4.size)

matrix generation in numpy
- array() # basic
- arange() # range of values with gap
- linspace() # range of values with equal gap
- logspace() # range of values with equal gap in log scale
- zeros() # array with all zeros
- ones() # array with all ones
- eye() # identity matrix
- diag() # diagonal matrix
- random.rand() # random matrix of given shape from 0 to 1
- random.randn() # random matrix of given shape from -1 to 1
- random.randint() # random matrix of given shape from given range

In [ ]:
# arange() function
x = np.arange(10)
print(x)
x1 = np.arange(-10,11,.5)
print(x1)
x2 = np.arange(-np.pi, np.pi, 2)
print(x2)
x3 = np.arange(1, 15, 2)
print(x3)

In [ ]:
x = np.linspace(0, 10, 10) # 5 numbers of elements
print(x)
x1 = np.linspace(0, 500, 100) # 5 numbers of elements
print(x1)

In [ ]:
z = np.zeros(10)
print(z)
z1 = np.zeros((2,3))
print(z1)

In [ ]:
o = np.ones((4,5))
print(o)

In [ ]:
e = np.eye(5,dtype=int)
print(e)

In [48]:
np.random.rand(3,3)

array([[0.04660685, 0.38974572, 0.8751144 ],
       [0.46140882, 0.46715852, 0.12607442],
       [0.07244268, 0.95423481, 0.25710286]])

In [49]:
np.random.randn(3,3)

array([[ 0.44701007, -1.85790451, -0.11433373],
       [-1.12340101,  0.67108296, -1.25177641],
       [-0.0435497 ,  0.66408198,  0.59667244]])

In [55]:
np.random.randint(11, 15, (5,5))

array([[11, 13, 12, 11, 13],
       [13, 11, 12, 13, 14],
       [11, 11, 12, 12, 13],
       [11, 14, 11, 13, 13],
       [12, 13, 12, 12, 12]])

matrix operations